/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nv;

import com.csvreader.CsvWriter;
import com.googlecode.javacv.FFmpegFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core.IplImage;
import com.nviso.nViso3DFIHttpClient;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;

import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

import org.jcodec.api.FrameGrab;

/**
 *
 * @author Kevin Georgy
 */
public class NVisoGuiMainFrame extends javax.swing.JFrame implements Observer {

	private String[][] photoFiles = {};
    private ProcessedImageListModel processedImageListModel = new ProcessedImageListModel();
    private ProcessedStream processedStream = new ProcessedStream();
    private ProcessedVideoListModel processedVideoListModel = new ProcessedVideoListModel();
    private ProcessedFileTableModel processedFileTableModel = null;
    private String initialAppId = "";
    private String initialAppKey = "";
    private ArrayList<ProcessedImage> processingList = new ArrayList<>();
    private ArrayList<ProcessedVideo> processingVideosList = new ArrayList<>();
    private nViso3DFIHttpClient client = null;
    private int blockStarts = 0;
    private int blockCount = 0;
    private int processedCount = 0;
    private int currentInBlockProcessed = -1;
    
    /**
     * Creates new form NVisoGuiMainFrame
     */
    public NVisoGuiMainFrame(String appId, String appKey) {
        initComponents();
        initialAppId = appId;
        initialAppKey = appKey;
        applicationIdText.setText(appId);
        applicationKeyText.setText(appKey);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	logoPanel = new javax.swing.JPanel() {
    		private Image image = null;
    		
    		@Override
    	    protected void paintComponent(Graphics g) {
    			super.paintComponent(g);
    			try {
					 if (image == null) image = ImageIO.read(new File("nviso_logo.png"));
					g.drawImage(image, 0, 0, this);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
    		}
    	};
    	//logoPanel.setBackground(Color.white);
    	logoPanel.setMinimumSize(new Dimension(500,100));
    	logoPanel.setMaximumSize(new Dimension(500,100));
    	
        applicationIdLabel = new javax.swing.JLabel();
        applicationKeyLabel = new javax.swing.JLabel();
        applicationIdText = new javax.swing.JTextField();
        applicationKeyText = new javax.swing.JTextField();
        //folderLabel = new javax.swing.JLabel();
        //folderPathLabel = new javax.swing.JLabel();
        selectFolderButtom = new javax.swing.JButton();
        selectStreamFolderButton = new javax.swing.JButton();
        selectVideoFolderButton = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        //jScrollPane1 = new javax.swing.JScrollPane();
        
        jPhotoTab = new javax.swing.JPanel();
        processPhotoMultiFaces = new javax.swing.JCheckBox("Detect multiple faces : ");
        processPhotoDistanceBox = new javax.swing.JComboBox();
        processPhotoDistanceLabel = new javax.swing.JLabel("Face distance : ");
        //processPhotoScrollPane = new javax.swing.JScrollPane();
        //folderImagesTable = new javax.swing.JTable();
        
        jStreamScrollPane = new javax.swing.JScrollPane();
        jVideoScrollPane = new javax.swing.JScrollPane();
        
        photoFileCounterLabel = new javax.swing.JLabel();
        
        folderImagesList = new javax.swing.JList();
        folderStreamList = new javax.swing.JList();
        folderVideosList = new javax.swing.JList();
        
        processAllButton = new javax.swing.JButton();
        saveToCsvButton = new javax.swing.JButton();
        serverLabel = new javax.swing.JLabel();
        serverText = new javax.swing.JTextField();
        processedPhotoPanel = new nv.ProcessedImagePanel();
        processedEmotionPanel = new nv.ProcessedEmotionPanel();
        processingProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        applicationIdLabel.setText("Application ID :");

        applicationKeyLabel.setText("Application Key :");

        //folderLabel.setText("Folder :");
        
        processedPhotoPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
            	if (jTabbedPane.getSelectedIndex() == 2){ // Video
            		processedPhotoPanel.increaseFrame();
            		processedPhotoPanel.updateVideoFrame();
	            	
	            	processedEmotionPanel.setProcessedImage((ProcessedVideo)folderVideosList.getSelectedValue(), processedPhotoPanel.getJsonFrame());
	            	
	            	//processedImagePanel.setProcessedImage(processedVideo);
	            	//folderVideosList.getSelectedValuesList().increaseFrame();
	            	
	            	/*this.setProcessedImage();
	            	image =1;*/
	            	//System.out.println("Click");
            	}
            }
         });
        
        /*javax.swing.GroupLayout processedImagePanelLayout = new javax.swing.GroupLayout(processedImagePanel);
        processedImagePanel.setLayout(processedImagePanelLayout);
        processedImagePanelLayout.setHorizontalGroup(
            processedImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        processedImagePanelLayout.setVerticalGroup(
            processedImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );*/
        
        processedEmotionPanel.setBackground(new java.awt.Color(255, 255, 255));
        
        
        JSplitPane processedPhotoFullPanel = new JSplitPane(JSplitPane.VERTICAL_SPLIT, processedPhotoPanel, processedEmotionPanel);
        processedPhotoFullPanel.setDividerLocation(200);//processedPhotoFullPanel.getDividerSize()/2);
        /*
        JPanel processedPhotoFullPanel = new JPanel();
        processedPhotoFullPanel.setLayout(new BoxLayout(processedPhotoFullPanel, BoxLayout.Y_AXIS));
        processedPhotoFullPanel.setBackground(Color.red);
        processedPhotoFullPanel.add(processedPhotoPanel);
        processedPhotoFullPanel.add(processedEmotionPanel);*/
        
        
        /*javax.swing.GroupLayout processedEmotionPanelLayout = new javax.swing.GroupLayout(processedEmotionPanel);
        processedEmotionPanel.setLayout(processedEmotionPanelLayout);
        processedEmotionPanelLayout.setHorizontalGroup(
            processedEmotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        processedEmotionPanelLayout.setVerticalGroup(
            processedEmotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );*/

        selectFolderButtom.setText("SELECT FOLDER");
        selectFolderButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFolderButtomActionPerformed(evt);
            }
        });
        
        selectStreamFolderButton.setText("Select stream");
        selectStreamFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStreamFolderButtonActionPerformed(evt);
            }
        });
        
        selectVideoFolderButton.setText("Select videos");
        selectVideoFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectVideoFolderButtonActionPerformed(evt);
            }
        });

        folderImagesList.setModel(processedImageListModel);
        folderImagesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                folderImagesListValueChanged(evt);
            }
        });
        
        
        
        /*processPhotoDistanceBox.addItem("near");
        processPhotoDistanceBox.addItem("medium");
        processPhotoDistanceBox.addItem("far");
        //processPhotoDistanceBox.setPreferredSize(new Dimension(100, 20));
        processPhotoDistanceBox.setAlignmentX(Component.LEFT_ALIGNMENT);
        processPhotoDistanceLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        JPanel photoDistance = new JPanel();
        photoDistance.setLayout(new BoxLayout(photoDistance, BoxLayout.X_AXIS));
        photoDistance.add(processPhotoDistanceLabel);
        photoDistance.add(processPhotoDistanceBox);
        processPhotoDistanceBox.setAlignmentX(Component.LEFT_ALIGNMENT);
        processPhotoDistanceLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        photoDistance.setAlignmentX(Component.LEFT_ALIGNMENT);
        //photoDistance.setBackground(Color.white);
        
        processPhotoMultiFaces.setHorizontalTextPosition(SwingConstants.LEFT);
        processPhotoMultiFaces.setAlignmentX(Component.LEFT_ALIGNMENT);
        */
        /*JPanel photoProcessConfiguration = new JPanel();
        photoProcessConfiguration.setLayout(new BoxLayout(photoProcessConfiguration, BoxLayout.X_AXIS));
        photoProcessConfiguration.add(processPhotoMultiFaces);
        photoProcessConfiguration.add(photoDistance);
        photoProcessConfiguration.setAlignmentX(Component.LEFT_ALIGNMENT);
        */
        
        photoFileCounterLabel.setText("Files loaded : 0");
        photoFileCounterLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        //jScrollPane1.setViewportView(folderImagesList);
        inputPhotoPanel = new JPanel();
        inputPhotoPanel.setLayout(new BoxLayout(inputPhotoPanel, BoxLayout.Y_AXIS));
        inputPhotoPanel.add(photoFileCounterLabel);// BorderLayout.NORTH);
        //inputPhotoPanel.add(selectFolderButtom); // BorderLayout.SOUTH);
        //inputPhotoPanel.add(processPhotoMultiFaces);
        //inputPhotoPanel.add(photoDistance);
        //inputPhotoPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        //inputPhotoPanel.setAlignmentY(Component.TOP_ALIGNMENT);
        inputPhotoPanel.setMaximumSize(new Dimension(150,40));
        //inputPhotoPanel.setSize(jScrollPane1.getWidth()/3, 20);
        
        /*processPhotoPanel = new JPanel();
        processPhotoPanel.setName("Process");
        processPhotoPanel.setSize(jScrollPane1.getWidth()/3, 20);
        processPhotoPanel.setBackground(Color.white);
        processPhotoPanel.setLayout(new BoxLayout(processPhotoPanel, BoxLayout.Y_AXIS));
        processPhotoPanel.add(processPhotoMultiFaces);
        processPhotoPanel.add(photoDistance);
        processPhotoPanel.add(processAllButton);
        processPhotoPanel.setSize(jScrollPane1.getWidth()/3, 20);
        
        exportPhotoPanel = new JPanel();
        exportPhotoPanel.setName("Export");
        exportPhotoPanel.setBackground(Color.white);
        exportPhotoPanel.add(saveToCsvButton);
        exportPhotoPanel.setSize(jScrollPane1.getWidth(), 20);*/
        
        
        
        
        String title[] = {"Filename", "Status"};
        processedFileTableModel = new ProcessedFileTableModel(title);
        folderImagesTable = new javax.swing.JTable(processedFileTableModel);
        photoScrollPane = new JScrollPane(folderImagesTable);
        folderImagesTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
            	folderImagesTableValueSelected(evt);
            }
         });
        
        //JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, inputPhotoPanel, processPhotoPanel);
        /*JPanel split = new JPanel();
        split.setLayout(new BorderLayout(5,0)); //new BoxLayout(split, BoxLayout.X_AXIS));
        split.add(inputPhotoPanel, BorderLayout.LINE_START);*/
        //split.add(processPhotoPanel, BorderLayout.CENTER);
        //split.add(exportPhotoPanel, BorderLayout.LINE_END);
        jPhotoTab.setLayout(new BorderLayout());
        //jScrollPane1.add(split, BorderLayout.NORTH);
        //jScrollPane1.add(inputPhotoPanel, BorderLayout.NORTH);
        jPhotoTab.add(photoScrollPane, BorderLayout.WEST);
        jPhotoTab.add(processedPhotoFullPanel, BorderLayout.CENTER);
        //jScrollPane1.add(processedEmotionPanel, BorderLayout.CENTER);
        jPhotoTab.setVisible(true);
        
        //jScrollPane1.add(selectFolderButtom);
        
        folderStreamList.setModel(processedStream.getImages());
        folderStreamList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                folderStreamListValueChanged(evt);
            }
        });
        jStreamScrollPane.setViewportView(folderStreamList);
        
        folderVideosList.setModel(processedVideoListModel);
        folderVideosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                folderVideosListValueChanged(evt); // does nothing for now
            }
        });
        jVideoScrollPane.setViewportView(folderVideosList);
        
        jTabbedPane.add("Photos", jPhotoTab);
        jTabbedPane.add("Stream", jStreamScrollPane);
        jTabbedPane.setEnabledAt(1, false);
        jTabbedPane.add("Videos", jVideoScrollPane);
        jTabbedPane.setEnabledAt(2, false);
        
        processAllButton.setText("PROCESS");
        processAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAllButtonActionPerformed(evt);
            }
        });

        saveToCsvButton.setText("EXPORT");
        saveToCsvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToCsvButtonActionPerformed(evt);
            }
        });

        serverLabel.setText("Server url : ");

        serverText.setText("http://nviso-apiv2-api.nviso.net/nviso/api/v2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applicationKeyLabel)
                            .addComponent(applicationIdLabel))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applicationIdText)
                            .addComponent(applicationKeyText, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serverLabel)
                        .addGap(33, 33, 33)
                        .addComponent(serverText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    	.addComponent(inputPhotoPanel)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(processingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        //.addComponent(processAllButton)
                        .addComponent(processAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        //.addComponent(selectVideoFolderButton)
                        .addComponent(saveToCsvButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        )//.addComponent(saveToCsvButton))
                    .addGroup(layout.createSequentialGroup()
                        //.addComponent(folderLabel)
                        //.addGap(47, 47, 47)
                        //.addComponent(folderPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFolderButtom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        //.addComponent(selectStreamFolderButton)
                        )
                    /*.addGroup(layout.createSequentialGroup()
                    		.addComponent(inputPhotoPanel))*/
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        /*.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            //.addComponent(processedEmotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            //.addComponent(processedImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            )*/
                        ))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                //.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoPanel)
                        //)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicationIdLabel)
                    .addComponent(applicationIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicationKeyLabel)
                    .addComponent(applicationKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverLabel)
                    .addComponent(serverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectFolderButtom)
                    //.addComponent(selectStreamFolderButton)
                    //.addComponent(selectVideoFolderButton)
                    //.addComponent(folderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    //.addComponent(folderPathLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                /*.addGroup(layout.createSequentialGroup()
                		.addComponent(inputPhotoPanel))*/
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        //.addComponent(processedImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        //.addComponent(processedEmotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    //.addComponent(processAllButton)
                    //.addComponent(saveToCsvButton)
                	.addComponent(inputPhotoPanel)
                    .addComponent(processingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processAllButton)
                    .addComponent(saveToCsvButton))
                .addContainerGap())
        );
        
        componentsInNormalState();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFolderButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFolderButtomActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose an image directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            
            // Clear the list
            processedImageListModel.clear();
            
            File folder = chooser.getSelectedFile();
            //this.folderPathLabel.setText(folder.toString());
      
            // Populate the list with the folder content
            File[] imagesFiles = folder.listFiles(new FilenameFilter() {

                @Override
                public boolean accept(File dir, String name) {
                    return name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png");
                }
                
            });
            photoFileCounterLabel.setText("Files loaded : "+ Integer.toString(imagesFiles.length));
            
            for (File f : imagesFiles) {
                processedImageListModel.addProcessedImage(new ProcessedImage(f));
                //String[] file = {f.getName(), "Not processed"};
                ((ProcessedFileTableModel)folderImagesTable.getModel()).addProcessedImage(new ProcessedImage(f));
            }
        }
        componentsInNormalState();
    }//GEN-LAST:event_selectFolderButtomActionPerformed
    
    private void selectStreamFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFolderButtomActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose an image directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            
        	if (processedStream == null){
            	processedStream = new ProcessedStream();
            }
            else {
            	processedStream.clear();
            }
            
            File folder = chooser.getSelectedFile();
            //this.folderPathLabel.setText(folder.toString());
      
            // Populate the list with the folder content
            File[] imagesFiles = folder.listFiles(new FilenameFilter() {

                @Override
                public boolean accept(File dir, String name) {
                    return name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png");
                }
                
            });
            
            for (File f : imagesFiles) {
                processedStream.addProcessedImage(new ProcessedImage(f));
            }
        }
        componentsInNormalState();
    }//GEN-LAST:event_selectFolderButtomActionPerformed
    
    private void selectVideoFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFolderButtomActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose an image directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            
            // Clear the list
            processedVideoListModel.clear();
            
            File folder = chooser.getSelectedFile();
            //this.folderPathLabel.setText(folder.toString());
      
            // Populate the list with the folder content
            File[] videosFiles = folder.listFiles(new FilenameFilter() {

                @Override
                public boolean accept(File dir, String name) {
                    return name.endsWith(".mp4");
                }
                
            });
            
            for (File f : videosFiles) {
                processedVideoListModel.addProcessedVideo(new ProcessedVideo(f));
            }
        }
        componentsInNormalState();
    }//GEN-LAST:event_selectFolderButtomActionPerformed
    
    private void initBlocks() {
        blockStarts = 0;
        blockCount = Math.min(10, processingList.size());
        currentInBlockProcessed = 0;
    }
    
    private void processNextBlock() {
        for (int i = blockStarts; i < blockStarts+blockCount; i++) {
            ProcessedImage current = processingList.get(i);
            int index = i;
            // Call the API
            Thread t = new Thread() {
            	public void run(){
            		client.processEmotionImageByUpload(current);
            	}
            };
            t.start();
            /*client.processEmotionImageByUpload(
                    current.getImagePath(), 
                    sessionIdText.getText(), 
                    "["+(i)+"]",
                    null,
                    null,//"batch",
                    "1",
                    "json", 
                    new ProcessedImageMashapeCallback(current),
                    (String) processPhotoDistanceBox.getSelectedItem(),
                    processPhotoMultiFaces.isSelected());
            */
        }
    }
    
    private void processSelectedList() {
        
        if (processingList.size() <= 0) {
            return;
        }
        // Disable ui component
        componentsInProcessingState();
        
        // Init the client
        client = new nViso3DFIHttpClient(
            applicationIdText.getText(),
            applicationKeyText.getText());
        
        // Set up the progress bar
        processingProgressBar.setMinimum(0);
        processingProgressBar.setMaximum(processingList.size());
        processingProgressBar.setValue(0);
        
        // Register this as observer of all images
        processedCount = 0;
        for (ProcessedImage current : processingList)
        {
            //ProcessedImage current = processedImageListModel.getElementAt(i);
            current.addObserver(this);
            current.setProcessing();
        }
        
        initBlocks();
        if (blockCount > 0) {
            processNextBlock();
        }
        
    }
    
    private void processSelectedStream() {
        /*if (processingList.size() <= 0) {
            return;
        }*/
        // Disable ui component
        componentsInProcessingState();
        
        // Init the client
        client = new nViso3DFIHttpClient(
            applicationIdText.getText(),
            applicationKeyText.getText());
        
        // Set up the progress bar
        processingProgressBar.setMinimum(0);
        processingProgressBar.setMaximum(processedStream.getImages().getSize());
        processingProgressBar.setValue(0);
        
        // Register this as observer of all images
        processedCount = 0;
        for (int i=0; i < processedStream.getImages().getSize(); ++i) //ProcessedImage current : processingList)
        {
            ProcessedImage current = processedStream.getImages().getElementAt(i);
            current.addObserver(this);
            current.setProcessing();
        }
        
        client.processEmotionStreamByUpload(
                processedStream);
    }
    
    private void processSelectedVideos() {
    	
        if (processingVideosList.size() <= 0) {
            return;
        }
        // Disable ui component
        componentsInProcessingState();
        
        // Init the client
        client = new nViso3DFIHttpClient(
            applicationIdText.getText(),
            applicationKeyText.getText());
        
        // Set up the progress bar
        processingProgressBar.setMinimum(0);
        processingProgressBar.setMaximum(processingVideosList.size());
        processingProgressBar.setValue(0);
        
        // Register this as observer of all images
        processedCount = 0;
        for (ProcessedVideo current : processingVideosList)
        {
            current.addObserver(this);
            current.setProcessing();
        }
        
        for (ProcessedVideo current : processingVideosList) {
        	client.processEmotionVideoByUpload(current);
        }
        
        /*client.processEmotionVideoByUpload(
                processedStream);
        for (int i = blockStarts; i < blockStarts+blockCount; i++) {
            ProcessedImage current = processingList.get(i);
            // Call the API
            client.processEmotionImageByUpload(
                    current.getImagePath(), 
                    sessionIdText.getText(), 
                    "["+(i)+"]",
                    null,
                    null,//"batch",
                    "1",
                    "json", 
                    new ProcessedImageMashapeCallback(current));
            
        }*/
    }
    
    private void processAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processAllButtonActionPerformed
    	if (jTabbedPane.getSelectedIndex() == 0){ // Photos
	        processingList.clear();
	        /*for (int i = 0; i < processedImageListModel.getSize(); i++) {
	            processingList.add(processedImageListModel.getElementAt(i));
	        }*/
	        for (int i = 0; i < processedFileTableModel.getRowCount(); i++) {
	            processingList.add(processedFileTableModel.getImageAt(i));
	        }
	        processSelectedList();
    	}
    	else if (jTabbedPane.getSelectedIndex() == 1){ // Stream
	        /*processingList.clear();
	        for (int i = 0; i < processedStream.getImages().getSize(); i++) {
	            processingList.add(processedStream.getImages().getElementAt(i));
	        }*/
	        processSelectedStream();
    	}
    	else if (jTabbedPane.getSelectedIndex() == 2){ // Video
    		processingVideosList.clear();
    		for (int i = 0; i < processedVideoListModel.getSize(); i++) {
	            processingVideosList.add(processedVideoListModel.getElementAt(i));
	        }
    		processSelectedVideos();
    	}
    }//GEN-LAST:event_processAllButtonActionPerformed

    private void saveToCsvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToCsvButtonActionPerformed
        // Choose CSV File
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Choose a CSV file");
        chooser.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if(f.isDirectory()) {return true;}
                return f.getName().endsWith(".csv");
            }

            @Override
            public String getDescription() {
                return "Csv file (*.csv)";
            }
        });
        
        if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File csvFile = chooser.getSelectedFile();
            if (!csvFile.getName().endsWith(".csv")) {
                JOptionPane.showMessageDialog(null,
                    csvFile.getName() + " is not a valid csv file name.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                    Date date = new Date();
                    boolean writeHeader = !csvFile.exists();
                    FileWriter fileWriter = new FileWriter(csvFile,true);
                    CsvWriter csvWriter = new CsvWriter(fileWriter,',');
                    // Write header if needed
                    if (writeHeader) {
                        csvWriter.write("File");
                        csvWriter.write("Date");
                        csvWriter.write("Session ID");
                        csvWriter.write("Frame ID");
                        for (String emo : ProcessedFace.ALL_EMOTIONS) {
                            csvWriter.write(emo);
                        }
                        csvWriter.write("No face found");
                        csvWriter.write("Error");
                        csvWriter.endRecord();
                    }
                    // Write value for each image
                    for (int i = 0; i < processedFileTableModel.getRowCount(); i++)
                    {
                        ProcessedImage current = processedFileTableModel.getImageAt(i);
                        if (current.getState() == ProcessedImage.State.Processed)
                        {
                            csvWriter.write(current.getImagePath().getName());
                            csvWriter.write(dateFormat.format(date));
                            //csvWriter.write(sessionIdText.getText());
                            csvWriter.write(Integer.toString(i));
                            // Face no face
                            if (current.getFaces().size() > 0) {
                                ProcessedFace face = current.getFaces().get(0);
                                for (String emo : ProcessedFace.ALL_EMOTIONS) {
                                    csvWriter.write(Double.toString(face.getEmotionProfile().get(emo)));
                                }
                                csvWriter.write("0");
                            } else {
                                for (String emo : ProcessedFace.ALL_EMOTIONS) {
                                    csvWriter.write("NaN");
                                }
                                csvWriter.write("1");
                            }
                            csvWriter.write(current.getProcessingStatusMessage());
                            csvWriter.endRecord();
                        }
                    }
                    csvWriter.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,
                        csvFile.getName() + " cannot be used ("+ex.getMessage()+")",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
                
                
            }
        }
    }//GEN-LAST:event_saveToCsvButtonActionPerformed
    
    private void folderImagesTableValueSelected(java.awt.event.MouseEvent evt) {
    	//String filename = (String) folderImagesTable.getValueAt(folderImagesTable.getSelectedRow(), 0);
    	processedPhotoPanel.setProcessedImage(processedFileTableModel.getImageAt(folderImagesTable.getSelectedRow()));
        processedEmotionPanel.setProcessedImage(processedFileTableModel.getImageAt(folderImagesTable.getSelectedRow()));
    }

    private void folderImagesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_folderImagesListValueChanged
    	processedPhotoPanel.setProcessedImage((ProcessedImage)folderImagesList.getSelectedValue());
        processedEmotionPanel.setProcessedImage((ProcessedImage)folderImagesList.getSelectedValue());
    }//GEN-LAST:event_folderImagesListValueChanged
    
    private void folderStreamListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_folderImagesListValueChanged
    	processedPhotoPanel.setProcessedImage((ProcessedImage)folderStreamList.getSelectedValue());
        processedEmotionPanel.setProcessedImage((ProcessedImage)folderStreamList.getSelectedValue());
    }//GEN-LAST:event_folderImagesListValueChanged
    
    private void folderVideosListValueChanged(javax.swing.event.ListSelectionEvent evt) {
    	processedPhotoPanel.setProcessedImage((ProcessedVideo)folderVideosList.getSelectedValue());//, 0);
    	processedEmotionPanel.setProcessedImage((ProcessedVideo)folderVideosList.getSelectedValue(), 0);
    }

    /*private void processSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processSelectedButtonActionPerformed
    	if (jTabbedPane.getSelectedIndex() == 0) { // Photos
	        processingList.clear();
	        processingList.addAll(folderImagesList.getSelectedValuesList());
	        processSelectedList();
    	}
    	else if (jTabbedPane.getSelectedIndex() == 2) { // Videos
    		processingVideosList.clear();
	        processingVideosList.addAll(folderVideosList.getSelectedValuesList());
	        processSelectedVideos();
    	}
        
    }//GEN-LAST:event_processSelectedButtonActionPerformed
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationIdLabel;
    private javax.swing.JTextField applicationIdText;
    private javax.swing.JLabel applicationKeyLabel;
    private javax.swing.JTextField applicationKeyText;
    private javax.swing.JList folderImagesList;
    private javax.swing.JTable folderImagesTable;
    private javax.swing.JList folderStreamList;
    private javax.swing.JList folderVideosList;
    
    //private javax.swing.JLabel folderLabel;
    //private javax.swing.JLabel folderPathLabel;
    
    private javax.swing.JPanel logoPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jPhotoTab;
    private javax.swing.JPanel inputPhotoPanel;
    private javax.swing.JLabel photoFileCounterLabel;
    private javax.swing.JPanel processPhotoPanel;
    private javax.swing.JCheckBox processPhotoMultiFaces;
    private javax.swing.JComboBox processPhotoDistanceBox;
    private javax.swing.JLabel processPhotoDistanceLabel;
    private javax.swing.JScrollPane photoScrollPane;
    
    private javax.swing.JPanel exportPhotoPanel;
    
    private javax.swing.JScrollPane jStreamScrollPane;
    private javax.swing.JScrollPane jVideoScrollPane;
    
    
    private javax.swing.JButton processAllButton;
    private nv.ProcessedEmotionPanel processedEmotionPanel;
    private nv.ProcessedImagePanel processedPhotoPanel;
    private javax.swing.JProgressBar processingProgressBar;
    private javax.swing.JButton saveToCsvButton;
    private javax.swing.JButton selectFolderButtom;
    private javax.swing.JButton selectStreamFolderButton;
    private javax.swing.JButton selectVideoFolderButton;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JTextField serverText;
    private javax.swing.JSplitPane photoSplit;
    
    // End of variables declaration//GEN-END:variables

    private void componentsInProcessingState() {
        applicationIdText.setEnabled(false);
        applicationKeyText.setEnabled(false);
        serverText.setEnabled(false);
        selectFolderButtom.setEnabled(false);
        saveToCsvButton.setEnabled(false);
        processAllButton.setEnabled(false);
        selectVideoFolderButton.setEnabled(false);
        selectStreamFolderButton.setEnabled(false);
    }
    
    private void componentsInNormalState() {
        applicationIdText.setEnabled(true);
        applicationKeyText.setEnabled(true);
        serverText.setEnabled(true);
        selectFolderButtom.setEnabled(true);
        if (folderImagesTable.getRowCount() != 0) saveToCsvButton.setEnabled(true);
        else saveToCsvButton.setEnabled(false);
        if (folderImagesTable.getRowCount() != 0) processAllButton.setEnabled(true);
        else processAllButton.setEnabled(false);
        selectVideoFolderButton.setEnabled(true);
        selectStreamFolderButton.setEnabled(true);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        // Some items in the list are updated ... update the progress
        
        synchronized(this) {
        	if(o.getClass().equals(ProcessedImage.class)) {
	            //int processedCount = 0;
	            //for (ProcessedImage current : processingList) {
	                //ProcessedImage current = processedImageListModel.getElementAt(i);
	                ProcessedImage current = (ProcessedImage)o;
	                if (current.getState() == ProcessedImage.State.Processed) {
	                    processedCount += 1;
	                    currentInBlockProcessed += 1;
	                }
	            //}
	            processingProgressBar.setValue(processedCount);
	            processingProgressBar.repaint();
	            // If block finished
	            if (currentInBlockProcessed == blockCount) {
	                currentInBlockProcessed = 0;
	                blockStarts = blockStarts+blockCount;
	                blockCount = Math.min(10, processingList.size()-blockStarts);
	                if (blockCount > 0) {
	                    processNextBlock();
	                }
	            }
	            // If processing finished
	            if (processedCount == processingList.size()) {
	                for (ProcessedImage cimg : processingList) {
	                    //ProcessedImage current = processedImageListModel.getElementAt(i);
	                    cimg.deleteObserver(this);
	                }
	                processedCount = 0;
	                currentInBlockProcessed = -1;
	                componentsInNormalState();
	            }
	        }
        	
        	else if(o.getClass().equals(ProcessedVideo.class)) {
	            //int processedCount = 0;
	            //for (ProcessedImage current : processingList) {
	                //ProcessedImage current = processedImageListModel.getElementAt(i);
	                ProcessedVideo current = (ProcessedVideo)o;
	                if (current.getState() == ProcessedVideo.State.Processed) {
	                    processedCount += 1;
	                    currentInBlockProcessed += 1;
	                }
	            //}
	            processingProgressBar.setValue(processedCount);
	            // If block finished
	            /*if (currentInBlockProcessed == blockCount) {
	                currentInBlockProcessed = 0;
	                blockStarts = blockStarts+blockCount;
	                blockCount = Math.min(10, processingList.size()-blockStarts);
	                if (blockCount > 0) {
	                    processNextBlock();
	                }
	            }*/
	            // If processing finished
	            if (processedCount == processingVideosList.size()) {
	                for (ProcessedVideo cvideo : processingVideosList) {
	                    //ProcessedImage current = processedImageListModel.getElementAt(i);
	                    cvideo.deleteObserver(this);
	                }
	                processedCount = 0;
	                currentInBlockProcessed = -1;
	                componentsInNormalState();
	            }
	        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Get the app_id and app_key from args
        String appId = "";
        String appKey = "";
        if (args.length == 2)
        {
           appId = args[0];
           appKey = args[1];
        }
        
        final String fAppId = appId;
        final String fAppKey = appKey;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NVisoGuiMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NVisoGuiMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NVisoGuiMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NVisoGuiMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NVisoGuiMainFrame(fAppId, fAppKey).setVisible(true);
            }
        });
    }
}
